name: Build examples

on: push

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["release-v4.4", "release-v5.0", "release-v5.1", "release-v5.2", "release-v5.3", "latest"]
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build examples
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager ruamel.yaml idf-build-apps --upgrade
          idf-build-apps build -p ./examples --recursive --target esp32s3